# Generated by Django 4.2 on 2023-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionresponse',
            old_name='response_date',
            new_name='response_time',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='question',
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question_ID',
            field=models.CharField(default='grade5/addition', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='response',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
