# Generated by Django 4.2 on 2023-05-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_questionresponse_response_peeked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionresponse',
            old_name='username',
            new_name='user',
        ),
    ]
