# Generated by Django 4.2 on 2023-05-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_username_questionresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='question_content',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
