# Generated by Django 4.2 on 2023-05-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expiration_date',
            field=models.DateTimeField(default=None),
        ),
    ]
